/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package routes;


import java.util.Arrays;
import java.util.HashSet;

/**
 *
 * @author Usuario
 */
public class FrmRoute extends javax.swing.JInternalFrame {
     

     
    
    Listdesnation list;
    Route rout;
    
    
    
    
    
    /**
     * Creates new form FrmRoute
     */
    public FrmRoute() {
        initComponents();
        this.BotAdd.setEnabled(false);
        this.btnUpdate.setEnabled(false);
        this.TxTSearch.setEnabled(false);
        this.setLocale(null);
         rout = new Listdesnation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BotAdd = new javax.swing.JButton();
        TxTSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxTCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxTDescripList = new javax.swing.JTextField();
        TxTDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxTName = new javax.swing.JTextField();
        TxTDelete1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Administrador de rutas de entrega");

        jPanel2.setBackground(new java.awt.Color(217, 246, 248));
        jPanel2.setForeground(new java.awt.Color(152, 202, 202));

        jPanel4.setBackground(new java.awt.Color(217, 246, 248));
        jPanel4.setDoubleBuffered(false);

        BotAdd.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        BotAdd.setForeground(new java.awt.Color(0, 0, 0));
        BotAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_add_64.png"))); // NOI18N
        BotAdd.setText("Agregar");
        BotAdd.setBorderPainted(false);
        BotAdd.setContentAreaFilled(false);
        BotAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotAdd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_add_72.png"))); // NOI18N
        BotAdd.setVerifyInputWhenFocusTarget(false);
        BotAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAddActionPerformed(evt);
            }
        });

        TxTSearch.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        TxTSearch.setForeground(new java.awt.Color(0, 0, 0));
        TxTSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search_64 (2).png"))); // NOI18N
        TxTSearch.setText("Buscar");
        TxTSearch.setBorderPainted(false);
        TxTSearch.setContentAreaFilled(false);
        TxTSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TxTSearch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search_72 (1).png"))); // NOI18N
        TxTSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TxTSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTSearchActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_receipt_64.png"))); // NOI18N
        btnUpdate.setText("Limpiar ");
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_receipt_72.png"))); // NOI18N
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Codigo");

        TxTCode.setBackground(new java.awt.Color(152, 202, 202));
        TxTCode.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TxTCode.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripcion");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Destinos ");

        TxTDescripList.setBackground(new java.awt.Color(152, 202, 202));
        TxTDescripList.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TxTDescripList.setForeground(new java.awt.Color(0, 0, 0));
        TxTDescripList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTDescripListActionPerformed(evt);
            }
        });

        TxTDescription.setBackground(new java.awt.Color(152, 202, 202));
        TxTDescription.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TxTDescription.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        TxTName.setBackground(new java.awt.Color(152, 202, 202));
        TxTName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TxTName.setForeground(new java.awt.Color(0, 0, 0));

        TxTDelete1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        TxTDelete1.setForeground(new java.awt.Color(0, 0, 0));
        TxTDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_cancel_64.png"))); // NOI18N
        TxTDelete1.setText("Eliminar");
        TxTDelete1.setBorderPainted(false);
        TxTDelete1.setContentAreaFilled(false);
        TxTDelete1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TxTDelete1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_cancel_72.png"))); // NOI18N
        TxTDelete1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TxTDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTDelete1ActionPerformed(evt);
            }
        });

        btnUpdate1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_update_64.png"))); // NOI18N
        btnUpdate1.setText("Actualizar");
        btnUpdate1.setBorderPainted(false);
        btnUpdate1.setContentAreaFilled(false);
        btnUpdate1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_update_72.png"))); // NOI18N
        btnUpdate1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BotAdd)
                        .addGap(42, 42, 42)
                        .addComponent(TxTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(TxTDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxTCode, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxTName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxTDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxTDescripList, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxTCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxTDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxTDescripList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TxTSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BotAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUpdate1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxTDelete1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 3, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_96.png"))); // NOI18N
        jLabel6.setText("Rutas de entrega");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAddActionPerformed
        int codes = Integer.parseInt(TxTCode.getText());
        String names = TxTName.getText();
        String descriptions = TxTDescription.getText();
        String[] descriptionsArray = TxTDescripList.getText().split(","); 
        HashSet<String> listDescriptionss = new HashSet<>(Arrays.asList(descriptionsArray));
        
        Route route = new Route(names, descriptions);
        list.addRount(list.toString()); 
       
        TxTCode.setText("");
        TxTName.setText("");
        TxTDescription.setText("");
        TxTDescripList.setText(""); 
        
        
    }//GEN-LAST:event_BotAddActionPerformed

    private void TxTDescripListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTDescripListActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_TxTDescripListActionPerformed

    private void TxTSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTSearchActionPerformed
      
      FrmSearchRoute frm = new FrmSearchRoute(null,true);
        frm.setList(list);
        //frm.Set(null);
        frm.setVisible(true);
        rout = frm.getRout();
        if (list!=null) {
            TxTCode.setText(String.valueOf(list.getCode()));
            TxTName.setText(list.getName());
            TxTDescription.setText(list.getDescription());
            String[] descriptionsArray = TxTDescripList.getText().split(","); 
        HashSet<String> listDescriptionss = new HashSet<>(Arrays.asList(descriptionsArray));
            this.btnUpdate.setEnabled(true);
            
            
    
       
    }//GEN-LAST:event_TxTSearchActionPerformed
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       
         list.deleteRoute(this.rout.getCode());
        this.TxTCode.setText("");
        this.TxTName.setText("");
        this.TxTDescription.setText("");
        rout = null;
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void TxTDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxTDelete1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAdd;
    private javax.swing.JTextField TxTCode;
    private javax.swing.JButton TxTDelete1;
    private javax.swing.JTextField TxTDescripList;
    private javax.swing.JTextField TxTDescription;
    private javax.swing.JTextField TxTName;
    private javax.swing.JButton TxTSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
