/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package shipments;

import customers.Customer;
import customers.CustomerList;
import customers.FrmSearchCustumer;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import packages.FrmSearchPackages;
import packages.PackagesList;
import packages.Package;
import routes.FrmSearchRoute;
import routes.Listdesnation;
import routes.Route;

/**
 *
 * @author Johel M
 */
public class FrmShipment extends javax.swing.JInternalFrame {

    private static int count = 1;
    private Shipment shipment;
    private Customer custom;
    private Package pack;
    private Route route;
    private double price;

    private CustomerList customers;
    private PackagesList paquetes;
    private Listdesnation routes;
    private ShipmentHistory history;
    private ShipmentQueue queue;

    /**
     * Creates new form FrmShipment
     */
    public FrmShipment() {
        initComponents();
        this.txtShipmentCode.setText(String.valueOf(count));

    }
    
    public void setListas(CustomerList customers,PackagesList paquetes,Listdesnation routes,
            ShipmentHistory history,ShipmentQueue queue){
        this.customers = customers;
        this.paquetes = paquetes;
        this.routes = routes;
        this.history = history;
        this.queue = queue;
    }

    public void customerIsNull() throws Exception {
        if (this.custom == null) {
            throw new Exception();
        }
    }

    public void packegeIsNull() throws Exception {
        if (this.pack == null) {
            throw new Exception();
        }
    }

    public void routeIsNull() throws Exception {
        if (this.route == null) {
            throw new Exception();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtShipmentDate = new javax.swing.JFormattedTextField();
        txtDeliveryDate = new javax.swing.JFormattedTextField();
        txtShipmentCode = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnConfir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCancelPack = new javax.swing.JButton();
        btnDispatchedPack = new javax.swing.JButton();
        btnDeliveredPack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnAddPack = new javax.swing.JButton();
        btnAddRoute = new javax.swing.JButton();
        btnAddClient = new javax.swing.JButton();
        txtClient = new javax.swing.JTextField();
        txtPack = new javax.swing.JTextField();
        txtRoute = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setTitle("Administracion de envios");
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(217, 246, 248));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 153, 255)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Numero de Envio");

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cliente");

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Paquete");

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ruta");

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha de Envio");

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Fecha de Entrega");

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Precio");

        txtShipmentDate.setEditable(false);
        txtShipmentDate.setBackground(new java.awt.Color(152, 202, 202));
        txtShipmentDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtShipmentDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtShipmentDate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtDeliveryDate.setEditable(false);
        txtDeliveryDate.setBackground(new java.awt.Color(152, 202, 202));
        txtDeliveryDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDeliveryDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDeliveryDate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtShipmentCode.setEditable(false);
        txtShipmentCode.setBackground(new java.awt.Color(152, 202, 202));
        txtShipmentCode.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtShipmentCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(152, 202, 202));
        txtPrice.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel2.setBackground(new java.awt.Color(217, 246, 248));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        btnAdd.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_add_64.png"))); // NOI18N
        btnAdd.setText("Guardar");
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setEnabled(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(0, 0, 0));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_receipt_64.png"))); // NOI18N
        btnNew.setText("Limpiar");
        btnNew.setBorderPainted(false);
        btnNew.setContentAreaFilled(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search_64 (2).png"))); // NOI18N
        btnSearch.setText("Buscar");
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Envio");

        btnConfir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnConfir.setForeground(new java.awt.Color(0, 0, 0));
        btnConfir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receipt_success_64.png"))); // NOI18N
        btnConfir.setText("Confirmar");
        btnConfir.setBorderPainted(false);
        btnConfir.setContentAreaFilled(false);
        btnConfir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConfir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addGap(36, 36, 36)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(new java.awt.Color(217, 246, 248));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        btnCancelPack.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnCancelPack.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelPack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/package_box_cancel_64.png"))); // NOI18N
        btnCancelPack.setText("Cancelar");
        btnCancelPack.setBorderPainted(false);
        btnCancelPack.setContentAreaFilled(false);
        btnCancelPack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelPack.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCancelPack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPackActionPerformed(evt);
            }
        });

        btnDispatchedPack.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnDispatchedPack.setForeground(new java.awt.Color(0, 0, 0));
        btnDispatchedPack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_information_64.png"))); // NOI18N
        btnDispatchedPack.setText("Despachar");
        btnDispatchedPack.setBorderPainted(false);
        btnDispatchedPack.setContentAreaFilled(false);
        btnDispatchedPack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDispatchedPack.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDispatchedPack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDispatchedPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispatchedPackActionPerformed(evt);
            }
        });

        btnDeliveredPack.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnDeliveredPack.setForeground(new java.awt.Color(0, 0, 0));
        btnDeliveredPack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_success_64.png"))); // NOI18N
        btnDeliveredPack.setText("Entregar");
        btnDeliveredPack.setBorderPainted(false);
        btnDeliveredPack.setContentAreaFilled(false);
        btnDeliveredPack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeliveredPack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_success_64.png"))); // NOI18N
        btnDeliveredPack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_success_72.png"))); // NOI18N
        btnDeliveredPack.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDeliveredPack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeliveredPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveredPackActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Paquete");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCancelPack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDispatchedPack)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeliveredPack)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeliveredPack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDispatchedPack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelPack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(217, 246, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agregar");

        btnAddPack.setBackground(new java.awt.Color(204, 204, 204));
        btnAddPack.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnAddPack.setForeground(new java.awt.Color(0, 0, 0));
        btnAddPack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/package_box_add_64.png"))); // NOI18N
        btnAddPack.setText("Paquete");
        btnAddPack.setBorderPainted(false);
        btnAddPack.setContentAreaFilled(false);
        btnAddPack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddPack.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAddPack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPackActionPerformed(evt);
            }
        });

        btnAddRoute.setBackground(new java.awt.Color(204, 204, 204));
        btnAddRoute.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnAddRoute.setForeground(new java.awt.Color(0, 0, 0));
        btnAddRoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/route_64.png"))); // NOI18N
        btnAddRoute.setText("Ruta");
        btnAddRoute.setBorderPainted(false);
        btnAddRoute.setContentAreaFilled(false);
        btnAddRoute.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddRoute.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAddRoute.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRouteActionPerformed(evt);
            }
        });

        btnAddClient.setBackground(new java.awt.Color(204, 204, 204));
        btnAddClient.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnAddClient.setForeground(new java.awt.Color(0, 0, 0));
        btnAddClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UserAdd_64.png"))); // NOI18N
        btnAddClient.setText("Cliente");
        btnAddClient.setBorderPainted(false);
        btnAddClient.setContentAreaFilled(false);
        btnAddClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddClient.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAddClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddRoute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddPack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAddRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtClient.setEditable(false);
        txtClient.setBackground(new java.awt.Color(152, 202, 202));
        txtClient.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtClient.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPack.setEditable(false);
        txtPack.setBackground(new java.awt.Color(152, 202, 202));
        txtPack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPack.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRoute.setEditable(false);
        txtRoute.setBackground(new java.awt.Color(152, 202, 202));
        txtRoute.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtRoute.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shipping_96.png"))); // NOI18N
        jLabel1.setText("Gestion de Envios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtShipmentDate)
                                        .addComponent(txtShipmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtClient, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(30, 30, 30)
                                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtShipmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtShipmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.txtShipmentCode.setText(String.valueOf(count));
        this.txtClient.setText("");
        this.txtShipmentDate.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        this.txtPack.setText("");
        this.txtDeliveryDate.setText("");
        this.txtRoute.setText("");
        this.txtPrice.setText("");

        this.custom = null;
        this.pack = null;
        this.route = null;

        this.btnConfir.setEnabled(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnConfirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirActionPerformed

        try {
            this.customerIsNull();
            this.packegeIsNull();
            this.routeIsNull();

            this.btnAdd.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Las casillas Cliente, Paquete o Ruta, no deben estar vacias");
        }

    }//GEN-LAST:event_btnConfirActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        shipment = new Shipment(custom, pack, route);
        this.txtPrice.setText(String.valueOf(shipment.getPrice()));
        this.history.addShipment(shipment);
        this.queue.addShipment(shipment);

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        FrmSearchShipment frm = new FrmSearchShipment(null, true);
        frm.setHistory(history);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.shipment = frm.getShipment();
        if (shipment != null) {
            this.txtShipmentCode.setText(String.valueOf(shipment.getShipmentNumber()));
            this.txtClient.setText(shipment.getClient().getName());
            this.txtShipmentDate.setText(shipment.getShipmentDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            this.txtPack.setText(shipment.getPack().getDescription());
            if(shipment.getPack().getState().Delivered.equals("Delivered")){
            this.txtDeliveryDate.setText(shipment.getDeliveryDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            }
            this.txtRoute.setText(shipment.getRoute().getName());
            this.txtPrice.setText(String.valueOf(shipment.getPrice()));
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        FrmSearchCustumer frm = new FrmSearchCustumer(null, true);
        frm.setList(customers);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.custom = frm.getCustom();
        if (custom != null) {
            this.txtClient.setText(custom.getName());
        }
    }//GEN-LAST:event_btnAddClientActionPerformed

    private void btnAddPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPackActionPerformed
        FrmSearchPackages frm = new FrmSearchPackages(null, true);
        frm.setList(paquetes);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.pack = frm.getPackage();
        if (pack != null) {
            this.txtPack.setText(pack.getDescription());
        }
    }//GEN-LAST:event_btnAddPackActionPerformed

    private void btnAddRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRouteActionPerformed
        FrmSearchRoute frm = new FrmSearchRoute(null, true);
        frm.setList(routes);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.route = frm.getRout();
        if (route != null) {
            this.txtRoute.setText(route.getName());
        }
    }//GEN-LAST:event_btnAddRouteActionPerformed

    private void btnCancelPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPackActionPerformed
        try {
            this.shipment.cancelShipment(pack);
            this.history.addShipment(shipment);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "El paquete debio estar En Almacén, para su Cancelación");
        }
    }//GEN-LAST:event_btnCancelPackActionPerformed

    private void btnDispatchedPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispatchedPackActionPerformed
        try {
            this.shipment.dispatchShipment(pack);
            this.history.addShipment(shipment);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "El paquete debio estar En Almacén, para su Despacho");
        }
    }//GEN-LAST:event_btnDispatchedPackActionPerformed

    private void btnDeliveredPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveredPackActionPerformed
        try {
            this.shipment.deliverShipment(pack);
            this.history.addShipment(shipment);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "El paquete debe estar Despachado, para completar la Entrega");
        }
    }//GEN-LAST:event_btnDeliveredPackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnAddPack;
    private javax.swing.JButton btnAddRoute;
    private javax.swing.JButton btnCancelPack;
    private javax.swing.JButton btnConfir;
    private javax.swing.JButton btnDeliveredPack;
    private javax.swing.JButton btnDispatchedPack;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtClient;
    private javax.swing.JFormattedTextField txtDeliveryDate;
    private javax.swing.JTextField txtPack;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoute;
    private javax.swing.JTextField txtShipmentCode;
    private javax.swing.JFormattedTextField txtShipmentDate;
    // End of variables declaration//GEN-END:variables
}
